[project]
name = "beverageorganiser"
version = "1.2.2"
description = "Getränkekasse"
requires-python = ">=3.11,<3.13"
dependencies = [
    "flet==1.0.3",
    "flet-lottie==1.0.3",
    "flet-camera==1.0.3",
    "flet-permission-handler==1.0.3",
    "pyjnius==1.6.1",
]

[tool.flet]
org = "de.jujfif"
product = "BeverageOrganiser"
company = "JuJ-FiF"
copyright = "Copyright © 2026 JuJ-FiF"
assets = ["assets"]
permissions = ["camera"]

[tool.flet.android.permissions]
"android.permission.REQUEST_INSTALL_PACKAGES" = true
"android.permission.CAMERA" = true

[tool.flet.template]
url = "C:\\FLET\\FletTemplates\\NoAndroidNavBar\\build"
